# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capstone_gui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1460, 781)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(200, 20, 1011, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius: 10px; \n"
"padding: 5px;  \n"
"border: 2px solid black;   ")
        self.Title.setObjectName("Title")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 150, 401, 431))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black;   ")
        self.widget.setObjectName("widget")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 121, 41))
        self.label_7.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius: 10px; \n"
"padding: 5px;  ")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 131, 41))
        self.label_9.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius: 10px; \n"
"padding: 5px;  ")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 91))
        self.label.setStyleSheet("border-image: url(:/newPrefix/images/free-icon-patient-1430453.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 290, 101, 91))
        self.label_2.setStyleSheet("border-image: url(:/newPrefix/images/free-icon-carer-2515014.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 70, 201, 31))
        self.comboBox_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"font: 75 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 290, 201, 31))
        self.comboBox_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"font: 75 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(1050, 150, 391, 431))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black;   ")
        self.widget_2.setObjectName("widget_2")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setGeometry(QtCore.QRect(40, 340, 301, 41))
        self.progressBar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: rgb(74, 74, 74);;;; /* 채워진 부분의 색상 */\n"
"    width: 20px; /* 높이 조절 */\n"
"}\n"
"\n"
" ")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 111, 41))
        self.label_8.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius: 10px; \n"
"padding: 5px;  ")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 261, 211))
        self.label_3.setStyleSheet("border-image: url(:/newPrefix/images/free-icon-person-standing-5557076.png);\n"
"border: 2px solid black; \n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1050, 620, 361, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"padding: 5px;  \n"
"border: 2px solid black;   ")
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 620, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"padding: 5px;  \n"
"border: 2px solid black;   ")
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 620, 361, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"padding: 5px;  \n"
"border: 2px solid black;   ")
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(430, 150, 611, 431))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black;   ")
        self.widget_3.setObjectName("widget_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_3)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 431, 171))
        self.textBrowser.setStyleSheet("border: 2px solid black")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 230, 431, 171))
        self.textBrowser_2.setStyleSheet("border: 2px solid black")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(480, 100, 111, 41))
        self.pushButton.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black;   ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 290, 111, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black;   ")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1460, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">자동 목욕 시스템</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">환자 정보</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">보호자 정보</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">진행도</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "중지"))
        self.pushButton_5.setText(_translate("MainWindow", "일시 중지"))
        self.pushButton_6.setText(_translate("MainWindow", "시작"))
        self.pushButton.setText(_translate("MainWindow", "확인"))
        self.pushButton_2.setText(_translate("MainWindow", "확인"))

        # ComboBox 시그널 연결 (환자와 보호자 정보 모두 연결)
        self.comboBox_2.clear()  # 이전 항목 제거
        self.comboBox_3.clear()  # 이전 항목 제거
        self.comboBox_2.currentIndexChanged.connect(self.on_patient_selected)
        self.comboBox_3.currentIndexChanged.connect(self.on_carer_selected)
        self.load_csv_data()


    def load_csv_data(self):
        csv_file = 'capstone.csv'  # CSV 파일의 경로로 변경하세요.

    # CSV 파일 읽기
        try:
                df = pd.read_csv(csv_file)
        
                # 첫 번째 열의 이름 열 값을 가져와 ComboBox에 추가하고, 나머지 정보를 딕셔너리에 저장
                self.person_info = {}
                first_column_values = df.iloc[:, 0].dropna().tolist()  # 첫 번째 열의 값들을 리스트로 추출
                
                for _, row in df.iterrows():
                        name = row['이름']  # '이름' 열의 값 가져오기
                        age = row['나이']  # '나이' 열의 값 가져오기
                        gender = row['성별']  # '성별' 열의 값 가져오기
                        weight = row['몸무게']  # '몸무게' 열의 값 가져오기

                        # ComboBox에 추가
                        self.comboBox_2.addItem(name)  # ComboBox에 이름 추가
                        self.comboBox_3.addItem(name)
                        # 나머지 정보들을 저장
                        self.person_info[name] = f"{name} - 성별: {gender}, 나이: {age}세, 몸무게: {weight}kg"

              

        except Exception as e:
                print("Error loading CSV data:", e)

    def show_patient_info(self, name):
        # ComboBox에서 선택된 이름에 해당하는 정보를 TextBrowser에 표시
        info_text = self.person_info.get(name, "선택한 사람에 대한 정보가 없습니다.")
        self.textBrowser.setText(info_text)

   # 보호자 정보 보여주기  
    def show_carer_info(self, name):
        # ComboBox에서 선택된 이름에 해당하는 정보를 TextBrowser에 표시
        info_text = self.person_info.get(name, "선택한 사람에 대한 정보가 없습니다.")
        self.textBrowser_2.setText(info_text)

    def on_patient_selected(self):
        # 환자 ComboBox에서 선택된 이름을 가져와 show_person_info 호출
        selected_name = self.comboBox_2.currentText()
        self.show_patient_info(selected_name)

    def on_carer_selected(self):
        # 보호자 ComboBox에서 선택된 이름을 가져와 show_person_info 호출
        selected_name = self.comboBox_3.currentText()
        self.show_carer_info(selected_name)

import resource_rc


if __name__ == "__main__":
    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
